-- AlterTable
ALTER TABLE "Config" ADD COLUMN     "bonusPointsPerHour" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "minRatio" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "requiredSeedingMinutes" INTEGER NOT NULL DEFAULT 4320;
